### ISSUE TITLE
about the size of GOPRO  dataset

### ISSUE THREAD

**Issue by linjing-ai** [zzh-tech/ESTRNN#11]
Hi,Thanks for your excellent work.
  You have mention that the size of a frame in GOPRO dataset is 1280x720, however, in the GOPRO_DS I downloaded from your link, the size is 960x540, so what's the correct size for the PSNR in your paper?
  Thanks you very much.

**Comment by zzh-tech** [comment]
Hi, the size in our paper is 960x540, which is the same as the GOPRO version used by IFIRNN.
The computational cost of each model is calculated for size of 1280x720.

**Comment by linjing-ai** [comment]
okay, thank you very much.
