### ISSUE TITLE
about the beam splitter system

### ISSUE THREAD

**Issue by ireneMsm2020** [zzh-tech/ESTRNN#13]
Where can we buy the beam splitter system? or is this made by yourself?

**Comment by zzh-tech** [comment]
It was made by ourselves.

**Comment by ireneMsm2020** [comment]
Thanks for your reply, and may i ask where we can buy the relay lens and beam splitter?

**Comment by zzh-tech** [comment]
Please contact this email (the co-author in charge of the hardware):
yqzheng@ai.u-tokyo.ac.jp
