### ISSUE TITLE
Why the psnr in github is different from that in paper?

### ISSUE THREAD

**Issue by linjing-ai** [zzh-tech/ESTRNN#14]
Hi, the psnr of BSD dataset you show in the github is lower than that in the paper? Could you please tell me about the reason?
paper:
![image](https://user-images.githubusercontent.com/70081899/118137319-a76be880-b437-11eb-8c6f-cf76eb594247.png)
github:
![image](https://user-images.githubusercontent.com/70081899/118137373-b94d8b80-b437-11eb-847c-59e4465375a3.png)

**Comment by zzh-tech** [comment]
Hi, there are two different versions of the BSD dataset.
The one on the Github is the new one.
We have improved the hardware and collected more data with 3 different settings.
The corresponding paper for the new BSD dataset is still under review.

**Comment by linjing-ai** [comment]
Okay, thank you very much.
