### ISSUE TITLE
About the psnr drop during testing

### ISSUE THREAD

**Issue by linjing-ai** [zzh-tech/ESTRNN#15]
Hi, I have trained a model on GOPRO dataset. During training ,the validation PSNR is 32.25 dB. However, during testing, the PSNR drops to 27.00dB. Are there any problem about this issue?
Thanks!

**Comment by zzh-tech** [comment]
Hi, I'm not sure what your problem is ...
Maybe you can provide more details (logs and checkpoints).

**Comment by linjing-ai** [comment]
Hi, could you please tell me the valid PSNR of GOPRO during training?  The log setup and output is as follow (I trained my model in my company, and it is not allowed to send package ):
![image](https://user-images.githubusercontent.com/70081899/119071302-222a9a00-ba1c-11eb-8939-93ed8989c191.png)
![image](https://user-images.githubusercontent.com/70081899/119071352-3e2e3b80-ba1c-11eb-9733-4deb14367e5b.png)

**Comment by zzh-tech** [comment]
> Hi, could you please tell me the valid PSNR of GOPRO during training?
I don't remember the exact values.
But, it seems OK based on your train and valid logs.

**Comment by linjing-ai** [comment]
Okay, I think that it may be caused by the resolution difference between valid and test phase.  Thank you very much.
