### ISSUE TITLE
Can you release the BSD dataset?

### ISSUE THREAD

**Issue by ChaoLi977** [zzh-tech/ESTRNN#17]
It seems that the Google Driver cannot download the BSD dataset now, can you please provide another link?

**Comment by zzh-tech** [comment]
Hi, thank you for pointing that out.
Google Drive shows that too many people have viewed or downloaded this file recently.
Can you try again after 24 hours?
If it doesn't work after 24 hours, I will upload the dataset to Baidu Wangpan and create a new link.

**Comment by ChaoLi977** [comment]
Yes, it still cannot be downloaded during these days. Thank you for uploading the dataset to another link.

**Comment by zzh-tech** [comment]
Hi, please try the link as below
https://drive.google.com/file/d/1fAPHmIQYpTekMkrIgV-zB0bawfzGHBUw/view?usp=sharing

Please give me feedback on whether it works or not, thanks.

**Comment by ChaoLi977** [comment]
The same problem still exists.

**Comment by zzh-tech** [comment]
Hi, I have asked some people to double check if these links are valid.
It turns out that both of these links could work.

**Comment by Iverson-zq** [comment]
Hi ,I have the same problem and have tired several times but still can not download the dataset

**Comment by Iverson-zq** [comment]
> The same problem still exists.

HI , Have you dowanloaded the dataset sucessfully?

**Comment by zzh-tech** [comment]
Hi, the reason is that there may have been too many download requests recently.
Please try again after maybe a day.

**Comment by Iverson-zq** [comment]
> Hi, the reason is that there may have been too many download requests recently.
> Please try again after maybe a day.

Thank you ,my god! I sovled the problem.I need to sign up for a Google cloud account.Thank you very much
