### ISSUE TITLE
Something about the training .

### ISSUE THREAD

**Issue by linjing7** [zzh-tech/ESTRNN#18]
Hi, thanks for your excellent work. I wonder that will it save some time if I change the "trainer_mode" from "dp" into "ddp"? I have 4 GPUs and it seems that it did not speed up ~

**Comment by zzh-tech** [comment]
Yes, the ddp mode in this code repository cannot work correctly.
It should be rewritten and the dataset in lmdb format will cause some problems.

**Comment by linjing-ai** [comment]
Okay, I'll try to rewritte it.

**Comment by lyw3074** [comment]
> Okay, I'll try to rewritte it.

Hi, could you share the rewritten ddp code？

**Comment by Iverson-zq** [comment]
> Okay, I'll try to rewritte it.

Hi, you are so cool . could you share the rewritten ddp code？
