### ISSUE TITLE
What are the hyper-parameter Settings for ESTRNN model training on the GOPRO dataset?

### ISSUE THREAD

**Issue by baize-a** [zzh-tech/ESTRNN#19]
Thank you for your excellent work.I retrain the model on the GOPROdataset but the best hyperparameters are not known.Can you tell me?(such as lr,lr_scheduler,end_epoch)

**Comment by zzh-tech** [comment]
Sorry, I only kept the hyper-parameters for BSD.
The default hyper-parameters should also work for GOPRO (but not the best).

**Comment by baize-a** [comment]
> Sorry, I only kept the hyper-parameters for BSD.
> The default hyper-parameters should also work for GOPRO (but not the best).



> Sorry, I only kept the hyper-parameters for BSD.
> The default hyper-parameters should also work for GOPRO (but not the best).

I see, thanks for your reply.
