### ISSUE TITLE
Will you provide a pretrained model?

### ISSUE THREAD

**Issue by GuideWsp** [zzh-tech/ESTRNN#2]

**Comment by zzh-tech** [comment]
This project was done during my internship at Huawei.
Unfortunately, I do not have permission to copy and publish the checkpoints of the pretrained model in Huawei's server.
Now, my personal GPUs are limited and I have other projects to work on.
So, I am currently unable to train the model again either.
Once we have collected the complete BSD dataset, I will experiment again and upload the checkpoints of the pretrained model.
Thank you.

**Comment by GuideWsp** [comment]
Thanks.
