### ISSUE TITLE
When only use past data?

### ISSUE THREAD

**Issue by jkpark0825** [zzh-tech/ESTRNN#20]
how was the PSNR, SSIM performance when only use past feature data in GSA stage in GOPRO, REDS, BSD?

**Comment by zzh-tech** [comment]
> how was the PSNR, SSIM performance when only use past feature data in GSA stage in GOPRO, REDS, BSD?

We did an experiment on GOPRO for this question.
Please see Table. 5 in our [ECCV paper](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123510188.pdf).
