### ISSUE TITLE
Hi, I want to know how to build up this beam splitter acquisition system?

### ISSUE THREAD

**Issue by ersanliqiao** [zzh-tech/ESTRNN#22]
Hello，Dear zzh: 
I want to collect motion blur paired data sets by myself. How can I build the  beam splitter   beam splitter  system shown in the paper? Where can I buy this system? Or what equipments should I buy to build up this system?

**Comment by zzh-tech** [comment]
Please contact Prof. Zheng (yqzheng@ai.u-tokyo.ac.jp), who is in charge of the hardware system.

**Comment by ersanliqiao** [comment]
> Please contact Prof. Zheng ([yqzheng@ai.u-tokyo.ac.jp](mailto:yqzheng@ai.u-tokyo.ac.jp)), who is in charge of the hardware system.

Thank you very much!!

**Comment by ersanliqiao** [comment]
> > Please contact Prof. Zheng ([yqzheng@ai.u-tokyo.ac.jp](mailto:yqzheng@ai.u-tokyo.ac.jp)), who is in charge of the hardware system.
> 
> Thank you very much!!

I have send email to Prof. Zheng, but he did'nt say anything usefull for me to build up this system

**Comment by ersanliqiao** [comment]
![image](https://user-images.githubusercontent.com/8411769/124872310-ad291900-dff7-11eb-894e-7728c3d73131.png)

**Comment by zzh-tech** [comment]
Hi, as Prof. Zheng said, it is not easy to build such a system.
You'd better consider establishing a cooperation with Prof. Zheng for your project rather than building it on your own.

**Comment by ersanliqiao** [comment]
> Hi, as Prof. Zheng said, it is not easy to build such a system.
> You'd better consider establishing a cooperation with Prof. Zheng for your project rather than building it on your own.

OK, thanks. I will consider it!
