### ISSUE TITLE
Old Version of BSD dataset

### ISSUE THREAD

**Issue by yzleroy** [zzh-tech/ESTRNN#23]
Hi, dear authors, have you provided old version of BSD dataset? I notice that in your eccv paper, there are two versions of BSD (15fps and 30fps), can you provide these two datasets? Since we want to cite your paper and compare your BSD results in your eccv paper.

**Comment by zzh-tech** [comment]
> Hi, dear authors, have you provided old version of BSD dataset?
> Can you provide these two datasets?

There are misalignment problems in the old version (start-aligned), and now we only keep the new one (center-aligned).
Thus, it's better to compare in the new version.
We also provide the qualitative and quantitative results for the new version.
See our journal paper (under review) as below:
[https://arxiv.org/abs/2106.16028](https://arxiv.org/abs/2106.16028)

**Comment by yzleroy** [comment]
ok，I understand，thank you for your quick reply:)



发自我的iPhone


------------------ Original ------------------
From: zzh-tech ***@***.***&gt;
Date: Thu,Jul 15,2021 1:51 PM
To: zzh-tech/ESTRNN ***@***.***&gt;
Cc: Leroy Lin ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zzh-tech/ESTRNN] Old Version of BSD dataset (#23)





  
Hi, dear authors, have you provided old version of BSD dataset?
 Can you provide these two datasets?
  
There are misalignment problems in the old version (start-aligned), and now we only keep the new one (center-aligned).
 Thus, it's better to compare in the new version.
 We also provide the qualitative and quantitative results for the new version.
 See our journal paper (under review) as below:
 https://arxiv.org/abs/2106.16028
