### ISSUE TITLE
Collab 

### ISSUE THREAD

**Issue by noobtoob4lyfe** [zzh-tech/ESTRNN#24]
Thanks for sharing this fantastic work.  
Would you consider make a Google Collab version available for less-techinically inclined folks like myself to try it out?  Thanks in advance.

**Comment by zzh-tech** [comment]
Sorry, no time to do that ...

**Comment by noobtoob4lyfe** [comment]
Really?  How long would it take?

**Comment by zzh-tech** [comment]
Hi, I have updated the inference code.
Please use "inference.py" as instructed in the README.md.

**Comment by noobtoob4lyfe** [comment]
Thanks!  Will have a look.
