### ISSUE TITLE
Something about the test

### ISSUE THREAD

**Issue by lyw3074** [zzh-tech/ESTRNN#26]
Hello! I use this code and the parameters in the paper to train on the GOPRO dataset. The results on the test set are lower than the results in the paper. If I want to accurately reproduce the results in the paper, what should I pay attention to?

**Comment by yzleroy** [comment]
> Hello! I use this code and the parameters in the paper to train on the GOPRO dataset. The results on the test set are lower than the results in the paper. If I want to accurately reproduce the results in the paper, what should I pay attention to?

Hi, What PSNR and SSIM have you achieved?

**Comment by lyw3074** [comment]
> > Hello! I use this code and the parameters in the paper to train on the GOPRO dataset. The results on the test set are lower than the results in the paper. If I want to accurately reproduce the results in the paper, what should I pay attention to?
> 
> Hi, What PSNR and SSIM have you achieved?

PSNR 29.04 SSIM 0.870

**Comment by Iverson-zq** [comment]
> > > Hello! I use this code and the parameters in the paper to train on the GOPRO dataset. The results on the test set are lower than the results in the paper. If I want to accurately reproduce the results in the paper, what should I pay attention to?
> > 
> > 
> > Hi, What PSNR and SSIM have you achieved?
> 
> PSNR 29.04 SSIM 0.870

Hi，  I use this code and the parameters in the paper to train on the GOPRO dataset. The LR=e-4, Loss=MSE, n_blocks=9, Channels=16X5=80, batchsize=4 but in the original paper, the batchsize = 8. The results on the test set are also lower than the results in the paper. My results: PSNR =29.1654 SSMI=0.8731. But in the original paper,  ESTRNN(B9C80) model‘s results :PSNR = 30.79 ,SSMI=0.9016

**Comment by zzh-tech** [comment]
The code has been modified based on the previous version.
Try to only change n_blocks=9 and keep the others as default.
Also, it is worth noting that the calculation of metrics in the paper for all models is patch-based.
This version is image-based (the performance for all models will vary accordingly).

**Comment by Iverson-zq** [comment]
> The code has been modified based on the previous version.
> Try to only change n_blocks=9 and keep the others as default.
> Also, it is worth noting that the calculation of metrics in the paper for all models is patch-based.
> This version is image-based (the performance for all models will vary accordingly).

Thank you for your reply. Due to my personal hardware environment is limited (single card 1080Ti, 12G), I set batchsize = 4, and change n_blocks=9, other parameters remain unchanged, the training results: PSNR  = 30.72, SSMI = 0.9094. Considering that I reduced batchsize , the result was 0.05 lower than the paper. All in all, thank you very much for your work. I am reproducing the results of your BSD dataset. Thanks again
