### ISSUE TITLE
About pretrained model 

### ISSUE THREAD

**Issue by CVHW** [zzh-tech/ESTRNN#28]
Hello, I really appreciate your work. I download your model and do not find the model trained on the GORPO dataset. Could you release this model? Thanks a lot .

**Comment by zzh-tech** [comment]
I cannot download the checkpoints for GOPRO from Huawei.
So, only checkpoints for BSD dataset.

**Comment by CVHW** [comment]
> I cannot download the checkpoints for GOPRO from Huawei.
> So, only checkpoints for BSD dataset.

Thank you for your reply. Moreover, can you divide the BSD dataset into many parts because of large size and release a new version?

**Comment by zzh-tech** [comment]
Please check the BaiduCloudDisk version:
[BSD 1ms8ms](https://pan.baidu.com/s/1i7iMOZVOvBWmNYi8zkQIpw), password: bsd1
[BSD 2ms16ms](https://pan.baidu.com/s/1ur-XHeNoSTPFQJwBVfbofQ), password: bsd2
[BSD 3ms24ms](https://pan.baidu.com/s/1QNJlxiduwbQzCypy-7Mlbw), password: bsd3
