### ISSUE TITLE
About training time of BSD dataset

### ISSUE THREAD

**Issue by Iverson-zq** [zzh-tech/ESTRNN#29]
- Dear Sir:

    Hello, thank you for your work! I am about to reproduce your paper. Could you tell me the training time of the model and the hardware environment of the experiment according to the requirements of the paper? Please forgive me, due to my personal hardware environment is limited (single card 1080Ti, 12G), so send an email to ask for your advice, look forward to your reply very much, thank you, I wish you a happy life thank you!

**Comment by zzh-tech** [comment]
single card 1080Ti, 12G, may not enough
please try to lower the batch size

**Comment by wangwyForNewTime** [comment]
你好同学，你还有BSD数据集嘛，能否发我一份呢，谷歌云现在无法下载该数据集，谢谢你
