### ISSUE TITLE
How can I use Multi-GPU training in your code

### ISSUE THREAD

**Issue by pp00704831** [zzh-tech/ESTRNN#3]
Hello,

I use the command like this 
' CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --data_root datasets --lr 1e-4 --batch_size 4 --num_gpus 4 --trainer_mode ddp ' 
to train on 4 GPU, but It seems like that model still works on single GPU.

Do your model support training on Multi-GPU or there is something wrong when I use Multi-GPU training?
![image](https://user-images.githubusercontent.com/57279608/100190957-418fb100-2f2a-11eb-95f4-a4e8f5968a07.png)

**Comment by pp00704831** [comment]
I have solved this problem, the reason is 4 2080ti GPU still can not accommodate the model when batch_size=4, so I use small batch_size to train.

**Comment by zzh-tech** [comment]
Actually, you can also adjust '--frames' to control the size.
Alternatively, '--trainer_mode dp' may work.

**Comment by pp00704831** [comment]
I got it. Thank you very much!
