### ISSUE TITLE
How to use with custom input ??

### ISSUE THREAD

**Issue by Entretoize** [zzh-tech/ESTRNN#30]
Hi, I just discovered you project and it's very impressive.
However I can't find how to use on my own video with pretrained model.
I put the images in a folder in the test directory (BSD/test/000/Blur/RGB/XXX.png ...) but the script seems to need also something in the sharp directory, I really don't understand, I tried to understand the script but I must not be searching in the right py as it uses blur and sharp directory.

Thanks fo any help

**Comment by zzh-tech** [comment]
Hi, I have updated the inference code.
Please use "inference.py" as instructed in the README.md.

**Comment by Entretoize** [comment]
Thank you, that's very cool !
