### ISSUE TITLE
Are these artifacts expected?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [zzh-tech/ESTRNN#32]
With the provide pre-trained models I keep getting these unsightly artifacts (compare the sky in these images).  Are these artifacts common with the REDS and GOPRO models as well?  Is there an available per-trained model that might avoid these artifacts?  Thanks!

![00000002_estrnn](https://user-images.githubusercontent.com/43832374/150200035-d1d378aa-d3c9-44ff-b776-17d62e009e1c.png)
Deblurred
![00000002_input](https://user-images.githubusercontent.com/43832374/150200048-e1d8e468-50a0-4101-ae96-80eb7e6ebf37.png)
Input

**Comment by zzh-tech** [comment]
Hi, maybe you can try the pre-trained models provided by the following project:
https://github.com/ljzycmd/SimDeblur

**Comment by noobtoob4lyfe** [comment]
Thanks for the reply.  I've gone over to the simdeblur project and I'm not able to find any ESTRNN checkpoint anywhere.  I looks like they updated their checkpoints yesterday here https://drive.google.com/drive/folders/1ukr-iLyxSMHVJJswHgGOF6QcQqOZwaLO .   Am I not seeing where to find ESTRNN checkpoints?

**Comment by zzh-tech** [comment]
Maybe you can leave some message (open a new issue on SimDeblur) asking @ljzycmd to update the checkpoint.

**Comment by noobtoob4lyfe** [comment]
will do. thanks!
