### ISSUE TITLE
Cannot download BSD dataset  

### ISSUE THREAD

**Issue by wangwyForNewTime** [zzh-tech/ESTRNN#35]
When I want to download BSD dataset from google drive , the warning is ：
抱歉，您目前无法查看或下载此文件。
最近查看或下载此文件的用户过多。请稍后再尝试访问此文件。如果您尝试访问的文件特别大或已与很多人共享，那么您最长可能需要等待 24 小时才能查看或下载该文件。如果您在 24 小时后仍然无法访问文件，请与您的网域管理员联系。

Please upload a new copy，thanks
Or can you upload to Baidu drive?

**Comment by zzh-tech** [comment]
Please try this link:
https://drive.google.com/file/d/1fAPHmIQYpTekMkrIgV-zB0bawfzGHBUw/view?usp=sharing

And it might be helpful to refer to this issue:
https://github.com/zzh-tech/ESTRNN/issues/17#issuecomment-922463894

**Comment by wangwyForNewTime** [comment]
> 
Thank you,the problem is solved.
