### ISSUE TITLE
Using pre-trained model to inference , the results is strange

### ISSUE THREAD

**Issue by wangwyForNewTime** [zzh-tech/ESTRNN#36]
I choose 15 pictures from BSD dataset to test
I use the comman：
`python inference.py --src  ./blur/  --dst  ./results/  --ckpt ./checkpoints/ESTRNN_C80B15_BSD_2ms16ms.tar`

the result is so strange 
![12](https://user-images.githubusercontent.com/49787222/184502317-8edcd917-0184-4ea8-8287-817b35a925ac.png)
![13](https://user-images.githubusercontent.com/49787222/184502370-e1336225-5fd5-4468-8771-863ae8852cc8.png)

I prepare a video to test
Use the comman:
`python inference.py --src 1.mp4  --dst ./results/2/ --ckpt ./checkpoints/ESTRNN_C80B15_BSD_2ms16ms.tar`
there is an error:
![14](https://user-images.githubusercontent.com/49787222/184520808-ea4dc4ae-d11e-4e5e-a25e-f8400fc2db88.png)

Anything I did wrong?

**Comment by zzh-tech** [comment]
Please share the test data with me. I'll check it for you later.

**Comment by wangwyForNewTime** [comment]
> Please share the test data with me. I'll check it for you later.

[BaiduDriverExtractCode：1024](https://pan.baidu.com/s/1s93FqWqUHfC_eUCHw164Ng)
There is my test data,I tried it on both windows and linux ,the results are same

**Comment by zzh-tech** [comment]
I tested the case with the BSD image sequence as input. There is no problem. The issue may be on your side.

Regarding the video, it seems that the actual number of frames does not match the number read by cv2. Anyway, I've updated the code that extracts frames from the video to avoid this.

**Comment by wangwyForNewTime** [comment]
> I tested the case with the BSD image sequence as input. There is no problem. The issue may be on your side.
> 
> Regarding the video, it seems that the actual number of frames does not match the number read by cv2. Anyway, I've updated the code that extracts frames from the video to avoid this.

Thank you for your reply
There is no error reminder when test BSD images ，I think the strange result maybe because of the  different  version of environment library version 
Accroding to ReadMe:
![11](https://user-images.githubusercontent.com/49787222/184529543-c09b5c87-aa1d-4904-9212-7bdf3633b5c7.png)
I use Annaconda to create a new environment,there is conda list:
![12](https://user-images.githubusercontent.com/49787222/184529610-f45d91d3-4381-452d-901f-7195c5ba1017.png)

It could be the version，can you give me the specific version which you are using?

**Comment by zzh-tech** [comment]
The list of dependencies of my current env (generated by pipreqs) is as follows for your reference:

lmdb==1.3.0
numpy==1.21.5
opencv_python==4.5.3.56
Pillow==9.2.0
rawpy==0.17.1
scikit_image==0.19.2
thop==0.1.0.post2207010342
torch==1.11.0
torchvision==0.12.0
tqdm==4.64.0

**Comment by wangwyForNewTime** [comment]
> The list of dependencies of my current env (generated by pipreqs) is as follows for your reference:
> 
> lmdb==1.3.0 numpy==1.21.5 opencv_python==4.5.3.56 Pillow==9.2.0 rawpy==0.17.1 scikit_image==0.19.2 thop==0.1.0.post2207010342 torch==1.11.0 torchvision==0.12.0 tqdm==4.64.0

Thank you,the problem is solved.
This is really version problem.Now coding runs smoothly
In addition to the above, also need python 3.7
