### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by jkpark0825** [zzh-tech/ESTRNN#37]
Thank you for the great work!

Is there any color mismatching or different intensity issue, during the collection of the dataset?

I think there might be some issues that come from the scattering of light or the refractive index of the beam splitter.

Thank you in advance!

**Comment by zzh-tech** [comment]
There is a little bit of color mismatching. It can be solved by offline calibration. ISP auto white balance can also be an option to solve this problem.
For more details, please contact Prof. Zheng (yqzheng@ai.u-tokyo.ac.jp).
