### ISSUE TITLE
Difference of GMACs

### ISSUE THREAD

**Issue by Stephen0808** [zzh-tech/ESTRNN#38]
I tested the GMACs with input (B, 8, 3, 1280, 720) of ESTRNN (version B9C90) but found something strange. If the input frames are 8, the output frames will be 4. So the total GMACs should be divided by 8 or 4? A extreme example is when the input frames are 5, the output will be just one image. But the model computed 5 frames in the RNN cell. To this point, I doubt the GMACs are related to the input frames' number instead of a variable decided by the model and input resolution.
Besides, could you share the settings of computing GMACs in your paper?

**Comment by zzh-tech** [comment]
> I doubt the GMACs are related to the input frames' number instead of a variable decided by the model and input resolution.

Hi, that's right. As the number of input frames increases, the average GMACs will be close to the actual value.
Thus, when computing GMACs in this paper, I modified the code to not count the GMACs (feature extraction in the cell) of the four frames, that do not have the corresponding output.
