### ISSUE TITLE
Cannot download BSD

### ISSUE THREAD

**Issue by aaaakshat** [zzh-tech/ESTRNN#39]
Hi team,
Excellent work. However, Google seems to be blocking BSD downloads due to download quotas. Is there any other way you can host BSD?

**Comment by Magauiya** [comment]
@aaaakshat, you can circumvent it by entering your google account. However, @zzh-tech even if I registered, downloading drops after 49 Gb.

**Comment by Magauiya** [comment]
Still can not download the dataset. Can you please help us?? @zzh-tech

**Comment by zzh-tech** [comment]
Please try this link:
https://drive.google.com/file/d/1fAPHmIQYpTekMkrIgV-zB0bawfzGHBUw/view

**Comment by zzh-tech** [comment]
This is strange. Yesterday, a user successfully downloaded the dataset using this link.
I'll upload a Baidu Wangpan version. Please wait.

**Comment by Magauiya** [comment]
I tried once more, but still the same issue. @zzh-tech Have you managed to upload the dataset to baidu?

**Comment by zzh-tech** [comment]
I am uploading to Baidu. Please wait.
BTW, please try this splited RGB version in google drive.
https://drive.google.com/drive/folders/1imcfS1oFpWF8Zn0volcDIHf7o7aVm1nk?usp=share_link

**Comment by zzh-tech** [comment]
Hi, I have uploaded the BaiduCloudDisk version:
[BSD 1ms8ms](https://pan.baidu.com/s/1i7iMOZVOvBWmNYi8zkQIpw), password: bsd1
[BSD 2ms16ms](https://pan.baidu.com/s/1ur-XHeNoSTPFQJwBVfbofQ), password: bsd2
[BSD 3ms24ms](https://pan.baidu.com/s/1QNJlxiduwbQzCypy-7Mlbw), password: bsd3
