### ISSUE TITLE
Issue on downloading BSD database

### ISSUE THREAD

**Issue by KSJhon** [zzh-tech/ESTRNN#40]
Dear Dr.Zhong!

Thank you for excellent work. I tried several times to download your BSD, but I failed. At the beginning, it looks like ok, but after going some amounts, it always shows "Failed-Network error", though other downloading works are successful.

Is it possible to share your database in another mode, e.g., splitting file or Baidu wangpan?

Thank you for your consideration.

Regards.

**Comment by zzh-tech** [comment]
Please try this link (do not forget to sign in your Google account):
https://drive.google.com/file/d/1fAPHmIQYpTekMkrIgV-zB0bawfzGHBUw/view

If it does not work, I'll upload a Baidu Wangpan version.

**Comment by KSJhon** [comment]
Thank you for your kindness!
After receiving your mail, I have tried, but still failed with same issue.
It goes well at beginning, but always breaks down.
If possible, please upload your dataset at BaiduNetdisk or others.


Thank you in advance.


Regards.






---- Replied Message ----
From Zhihang ***@***.***>Date 12/12/2022 23:22To ***@***.***>Cc ***@***.***> ,
 ***@***.***>Subject Re: [zzh-tech/ESTRNN] Issue on downloading BSD database (Issue #40)

Please try this link (do not forget to sign in your Google account):
 https://drive.google.com/file/d/1fAPHmIQYpTekMkrIgV-zB0bawfzGHBUw/view
If it does not work, I'll upload a Baidu Wangpan version.

**Comment by zzh-tech** [comment]
I am uploading to Baidu. Please wait.
BTW, please try this splited RGB version in google drive:
https://drive.google.com/drive/folders/1imcfS1oFpWF8Zn0volcDIHf7o7aVm1nk?usp=share_link

**Comment by zzh-tech** [comment]
Hi, I have uploaded the BaiduCloudDisk version:
[BSD 1ms8ms](https://pan.baidu.com/s/1i7iMOZVOvBWmNYi8zkQIpw), password: bsd1
[BSD 2ms16ms](https://pan.baidu.com/s/1ur-XHeNoSTPFQJwBVfbofQ), password: bsd2
[BSD 3ms24ms](https://pan.baidu.com/s/1QNJlxiduwbQzCypy-7Mlbw), password: bsd3
