### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by yanhui1111** [zzh-tech/ESTRNN#41]
您好，请问这个支持用CPU训练或者推理吗

**Comment by jinzi98** [comment]
CPU还是算了吧，他这个模型很大，几百万参数，源代码提供dp和ddp训练方式，我dp用40G的A100跑都得几天。你要想跑可以租一下云服务器。

**Comment by yanhui1111** [comment]
好的谢谢



| |
yanhui_199903
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月09日 15:31 |
| 收件人 | ***@***.***> |
| 抄送至 | 2021103218 ***@***.***>***@***.***> |
| 主题 | Re: [zzh-tech/ESTRNN] CPU (Issue #41) |

CPU还是算了吧，他这个模型很大，几百万参数，源代码提供dp和ddp训练方式，我dp用40G的A100跑都得几天。你要想跑可以租一下云服务器。
