### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by jkpark0825** [zzh-tech/ESTRNN#42]
First of all, thank you for the great work.

In the BSD dataset, the beam splitter divides the light to create two images with different exposure times, but there could be some misalignment between the paired images. Is any additional method employed to align the misaligned pixels in these images?

Thank you in advance.

**Comment by zzh-tech** [comment]
> there could be some misalignment between the paired images

We use a laser to physically make the misalignment less.

> Is any additional method employed to align the misaligned pixels in these images?

And post-processing (homography) is applied to ensure that the misalignment is less than 1 pixel.
