### ISSUE TITLE
About test datasets settings

### ISSUE THREAD

**Issue by DachunKai** [zzh-tech/ESTRNN#45]
Hi, when testing on BSD 1ms8ms, did you use the model trained from scratch on 1ms8ms? Also, when testing on 2ms16ms, did you use the model trained on 1ms8ms from scratch?

**Comment by zzh-tech** [comment]
> Hi, when testing on BSD 1ms8ms, did you use the model trained from scratch on 1ms8ms? 

Yes, for testing on each BSD setting, we used a model trained from scratch using the data from that corresponding setting.
