### ISSUE TITLE
A question about the test output

### ISSUE THREAD

**Issue by YDDDDG** [zzh-tech/ESTRNN#6]
Hi,

Sorry to bother you. 

I have a question about the _test.py_ output.

I found that when I test the model with a sequence, frames indexing from 1 to 300, the output sequence's frames only range from 3 to 297. Frame 1, 2, 298, 299, 300 are lost.  Why does this happen? What should I do If I want to get the lost frames?

**Comment by zzh-tech** [comment]
> Why does this happen?

Because the default model use features from two future frames and two past frames.

> What should I do If I want to get the lost frames?

You can duplicate the start and end frames twice, making the sequence have 304 frames.

**Comment by YDDDDG** [comment]
A simple and easy to understand reply, thank you @zzh-tech
