### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType' !!!!!

### ISSUE THREAD

**Issue by Zz1041328406** [zzh-tech/ESTRNN#8]
hello !  
When I test my dataset, first I change my own dataset into lmdb. Then when I test,I had the problem in test.py.
after encode ,the blur_img is none.
![屏幕截图 2021-03-09 221245](https://user-images.githubusercontent.com/77730893/110483486-b4611880-8124-11eb-95a2-a4834a3bb1b8.png)
the error is ![1](https://user-images.githubusercontent.com/77730893/110483725-f7bb8700-8124-11eb-94bf-cb1760a35756.png)

can you tell me more about test part.
Thanks!

**Comment by zzh-tech** [comment]
Hi, I think the problem is in the lmdb file you made.
When you create the lmdb file, it reads NoneType for that seq_idx and frame_idx (no such image was found).
