### ISSUE TITLE
Average PSNR drops when testing a sequence checkpoint

### ISSUE THREAD

**Issue by mjc619** [zzh-tech/ESTRNN#9]
when testing the best checkpoint, which when the sequence is in /valid the PSNR is 36.038 during training, the same sequences (renamed to /test) will have a PSNR of 27.366(the same or even blurrier as what's being fed in as the blur)
it is applying some change, but it's not sharpening the image.
Input
![00000088_input](https://user-images.githubusercontent.com/8377727/111925588-83afa600-8a77-11eb-9d8b-4365124ce066.png)
ESTRNN
![00000088_estrnn](https://user-images.githubusercontent.com/8377727/111925473-ff5d2300-8a76-11eb-983e-34ed5a36e14c.png)
GT
![00000088_gt](https://user-images.githubusercontent.com/8377727/111925474-fff5b980-8a76-11eb-9809-95d6a496372c.png)

**Comment by zzh-tech** [comment]
Hi, could you please send me the checkpoint (including log) and the data sequence?
I may check for it for you sometime.

**Comment by mjc619** [comment]
results are sharpening above 28psnr but require a lot more epochs (>800) for some scenes than the default 500, although that may depend more or less on the type of sharpening being done (resolving real blur vs generated) and dataset size.
